const contactModal = document.querySelector('#contactModal');
const contactList = document.querySelector('#emergencyContacts');
const addContactButton = document.querySelector('#addContact');
const savedAccount = JSON.parse(localStorage.getItem('sahayaAccount') || 'null');
if (savedAccount && savedAccount.name) document.querySelector('#userGreeting').textContent = `Hello ${savedAccount.name}`;
const savedContacts = JSON.parse(localStorage.getItem('sahaayaEmergencyContacts') || '[]');
function contactInitials(name) { return name.split(/\s+/).map(part => part[0]).slice(0, 2).join('').toUpperCase(); }
function addContactToPage(contact) { const item=document.createElement('article'); item.innerHTML=`<b>${contactInitials(contact.name)}</b><span><strong>${contact.name}</strong><small>${contact.relationship} · ${contact.phone}</small></span><button class="remove-emergency-contact" aria-label="Remove ${contact.name}">×</button>`; item.querySelector('button').onclick=()=>{const index=savedContacts.findIndex(c=>c.id===contact.id);if(index>-1)savedContacts.splice(index,1);localStorage.setItem('sahaayaEmergencyContacts',JSON.stringify(savedContacts));item.remove();}; contactList.insertBefore(item,addContactButton); }
savedContacts.forEach(addContactToPage);
addContactButton.onclick=()=>{contactModal.classList.add('open');contactModal.setAttribute('aria-hidden','false');document.querySelector('#contactName').focus();};
document.querySelector('#closeContactModal').onclick=()=>{contactModal.classList.remove('open');contactModal.setAttribute('aria-hidden','true');};
contactModal.onclick=e=>{if(e.target===contactModal)document.querySelector('#closeContactModal').click();};
document.querySelector('#contactForm').onsubmit=e=>{e.preventDefault();const contact={id:Date.now(),name:document.querySelector('#contactName').value.trim(),phone:document.querySelector('#contactPhone').value.trim(),relationship:document.querySelector('#contactRelationship').value.trim()};savedContacts.push(contact);localStorage.setItem('sahaayaEmergencyContacts',JSON.stringify(savedContacts));addContactToPage(contact);e.currentTarget.reset();document.querySelector('#closeContactModal').click();const toast=document.querySelector('#toast');toast.textContent='Emergency contact added.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3000);};
document.querySelector('#accountForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#accountName').value.trim(),email=document.querySelector('#accountEmail').value.trim(),password=document.querySelector('#accountPassword').value;localStorage.setItem('sahayaAccount',JSON.stringify({name,email,password}));document.querySelector('#userGreeting').textContent=`Hello ${name}`;document.querySelector('#accountStatus').textContent='Account created successfully. You can now sign in.';e.currentTarget.reset();};
document.querySelector('#loginForm').onsubmit=e=>{e.preventDefault();const account=JSON.parse(localStorage.getItem('sahayaAccount')||'null'),email=document.querySelector('#loginEmail').value.trim(),password=document.querySelector('#loginPassword').value,status=document.querySelector('#loginStatus');if(!account){status.textContent='No account found. Please create an account first.';status.style.color='var(--coral)';return;}if(account.email!==email||account.password!==password){status.textContent='Email or password is incorrect.';status.style.color='var(--coral)';return;}document.querySelector('#userGreeting').textContent=`Hello ${account.name}`;status.textContent=`Signed in as ${account.name}.`;status.style.color='#287a5b';location.hash='home';};
