(() => {
  const $ = (selector) => document.querySelector(selector);
  const sosButton = $('#sosButton'), sosStatus = $('#sosStatus'), sosControls = $('#sosProgress');
  const sosCountdown = $('#sosCountdown'), cancelButton = $('#cancelSos');
  if (!sosButton) return;
  let cancelTimer, countdownTimer, locationWatchId, alertActive = false;
  const notify = (message) => { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(window.sosToastTimer); window.sosToastTimer = setTimeout(() => toast.classList.remove('show'), 3000); };
  const reset = (message) => { clearTimeout(cancelTimer); clearInterval(countdownTimer); if (locationWatchId) navigator.geolocation.clearWatch(locationWatchId); locationWatchId = undefined; alertActive = false; sosButton.disabled = false; sosButton.innerHTML = '<span>!</span> Send SOS'; sosControls.hidden = true; cancelButton.disabled = false; sosStatus.textContent = message; };
  const renderLocation = ({ coords }) => { const { latitude, longitude, accuracy } = coords; $('#coordinates').textContent = `GPS: ${latitude.toFixed(6)}, ${longitude.toFixed(6)} (±${Math.round(accuracy)} m)`; $('#sosMap').classList.add('location-ready'); $('#locationEmpty').textContent = 'Live GPS location attached to this SOS alert.'; };
  const confirmAlert = () => { alertActive = true; sosButton.innerHTML = '<span>✓</span> SOS sent'; sosControls.hidden = false; sosStatus.textContent = 'Emergency alert sent: “Emergency! I need immediate assistance. My current location is attached.”'; notify('SOS alert sent successfully.'); let remaining = 10; sosCountdown.textContent = `Alert sent. Cancel SOS within ${remaining} seconds.`; countdownTimer = setInterval(() => { remaining -= 1; sosCountdown.textContent = remaining > 0 ? `Alert sent. Cancel SOS within ${remaining} seconds.` : 'Alert delivery is now confirmed.'; if (remaining <= 0) { clearInterval(countdownTimer); cancelButton.disabled = true; } }, 1000); cancelTimer = setTimeout(() => { sosControls.hidden = true; }, 10000); };
  sosButton.addEventListener('click', (event) => { event.stopImmediatePropagation(); if (!navigator.geolocation) { sosStatus.textContent = 'Location services are unavailable. Please call emergency services directly.'; return; } sosButton.disabled = true; sosButton.innerHTML = '<span>…</span> Finding your location…'; sosStatus.textContent = 'Requesting your current GPS location…'; navigator.geolocation.getCurrentPosition((position) => { renderLocation(position); locationWatchId = navigator.geolocation.watchPosition(renderLocation, () => {}, { enableHighAccuracy: true, maximumAge: 5000 }); confirmAlert(); }, () => reset('We could not access your location. Please allow location access and try again, or call emergency services directly.'), { enableHighAccuracy: true, timeout: 10000, maximumAge: 0 }); }, true);
  cancelButton.addEventListener('click', () => { if (alertActive) { reset('SOS alert cancelled before delivery confirmation.'); notify('SOS alert cancelled.'); } });
})();
