const splash=document.querySelector('#splashScreen');
document.querySelector('#startSahaya').onclick=()=>{splash.classList.add('hidden');location.hash='login';};
const profileSetup=document.querySelector('#profileSetupModal');
function openProfileSetup(){profileSetup.classList.add('open');profileSetup.setAttribute('aria-hidden','false');}
document.querySelector('#accountForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#accountName').value.trim(),email=document.querySelector('#accountEmail').value.trim(),password=document.querySelector('#accountPassword').value;localStorage.setItem('sahayaAccount',JSON.stringify({name,email,password}));document.querySelector('#userGreeting').textContent=`Hello ${name}`;openProfileSetup();};
document.querySelector('#profileSetupForm').onsubmit=e=>{e.preventDefault();const account=JSON.parse(localStorage.getItem('sahayaAccount')||'{}');account.mobility=document.querySelector('input[name="setupMobility"]:checked').value;account.avoidStairs=document.querySelector('#setupAvoidStairs').checked;account.wideDoors=document.querySelector('#setupWideDoors').checked;localStorage.setItem('sahayaAccount',JSON.stringify(account));profileSetup.classList.remove('open');location.hash='home';document.querySelector('#toast').textContent='Profile created. Your routes are now personalized.';document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),3000);};
const indoorCopy=document.querySelector('#indoor .indoor-copy');
const indoorTools=document.createElement('div');indoorTools.className='indoor-tools';indoorTools.innerHTML='<label>Building <select id="buildingSelect"><option>City Care Hospital</option><option>Central Station</option><option>Orchard Square Mall</option></select></label><label>Floor <select id="floorSelect"><option>Ground floor</option><option>First floor</option><option>Second floor</option></select></label><button class="button coral" id="showIndoorRoute" type="button">Show accessible route →</button><div id="indoorStatus" aria-live="polite"></div>';indoorCopy.querySelector('.legend').after(indoorTools);
document.querySelector('#showIndoorRoute').onclick=()=>{const building=document.querySelector('#buildingSelect').value,floor=document.querySelector('#floorSelect').value;document.querySelector('#indoorStatus').className='journey-status';document.querySelector('#indoorStatus').textContent=`${building}, ${floor}: step-free route highlighted to elevator, accessible washroom, and exit.`;};
const routeForm=document.querySelector('#routeForm');routeForm.addEventListener('submit',()=>setTimeout(()=>{const result=document.querySelector('#routeResult');result.insertAdjacentHTML('beforeend',' <button class="button dark" id="startNavigation" type="button">Start navigation →</button>');document.querySelector('#startNavigation').onclick=()=>{document.querySelector('#journeyRating').scrollIntoView({behavior:'smooth'});};},0));
const rating=document.createElement('section');rating.id='journeyRating';rating.className='rating-card';rating.innerHTML='<p class="eyebrow"><span></span> Arrival check-in</p><h2>How accessible was your journey?</h2><p>Your rating helps wheelchair users plan with confidence.</p><div class="rating-stars">'+[1,2,3,4,5].map(n=>`<button data-rating="${n}" aria-label="Rate ${n} stars">★</button>`).join('')+'</div><textarea placeholder="Share a note about ramps, elevators, or obstacles..."></textarea><button id="submitRating" class="button coral">Share accessibility rating →</button><p id="ratingStatus" aria-live="polite"></p>';document.querySelector('#routes').after(rating);
document.querySelectorAll('.rating-stars button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.rating-stars button').forEach(star=>star.classList.toggle('selected',Number(star.dataset.rating)<=Number(button.dataset.rating)));rating.dataset.rating=button.dataset.rating;});
document.querySelector('#submitRating').onclick=()=>{document.querySelector('#ratingStatus').textContent=`Thank you for your ${rating.dataset.rating||5}-star accessibility rating.`;};
