"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { ReactNode, useEffect, useState } from "react";
import { FaBell, FaHome, FaMapMarkedAlt, FaCamera, FaMapPin, FaUsers, FaHeart, FaExclamationTriangle, FaUser, FaCog, FaWheelchair, FaBars, FaTimes, FaMoon, FaSun } from "react-icons/fa";
import { useAuth } from "./auth-provider";
const nav = [{ href: "/dashboard", label: "Home", icon: FaHome }, { href: "/navigation", label: "Navigation", icon: FaMapMarkedAlt }, { href: "/scanner", label: "Scanner", icon: FaCamera }, { href: "/nearby", label: "Nearby Places", icon: FaMapPin }, { href: "/community", label: "Community", icon: FaUsers }, { href: "/health", label: "Health", icon: FaHeart }, { href: "/emergency", label: "Emergency", icon: FaExclamationTriangle }, { href: "/profile", label: "Profile", icon: FaUser }, { href: "/settings", label: "Settings", icon: FaCog }];
export function AppShell({ title, children }: { title: string; children: ReactNode }) { const path = usePathname(); const router = useRouter(); const { user, loading } = useAuth(); const [menuOpen, setMenuOpen] = useState(false); const [dark, setDark] = useState(false);
 useEffect(() => { if (!loading && !user) router.replace("/login"); }, [loading, user, router]); useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
 if (loading || !user) return <main className="grid min-h-screen place-items-center"><div role="status" className="h-9 w-9 animate-spin rounded-full border-4 border-brand-500 border-t-transparent" aria-label="Loading Sahaya" /></main>;
 return <div className="min-h-screen md:flex"><aside className={`${menuOpen ? "translate-x-0" : "-translate-x-full"} fixed z-30 h-full w-72 bg-brand-700 p-5 text-white transition-transform md:static md:translate-x-0`}><Link href="/dashboard" className="mb-9 flex items-center gap-3 text-2xl font-bold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white text-brand-700"><FaWheelchair /></span>Sahaya</Link><nav aria-label="Main navigation" className="space-y-1">{nav.map(({ href, label, icon: Icon }) => <Link onClick={() => setMenuOpen(false)} key={href} href={href} className={`flex items-center gap-3 rounded-xl px-4 py-3 font-medium ${path === href ? "bg-white text-brand-700" : "hover:bg-white/15"}`}><Icon aria-hidden />{label}</Link>)}</nav></aside>{menuOpen && <button onClick={() => setMenuOpen(false)} className="fixed inset-0 z-20 bg-black/40 md:hidden" aria-label="Close navigation menu" />}
 <section className="min-w-0 flex-1"><header className="surface sticky top-0 z-10 flex h-20 items-center justify-between border-b bg-white px-4 md:px-8"><div className="flex items-center gap-3"><button onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg p-2 text-xl md:hidden" aria-label="Open navigation menu">{menuOpen ? <FaTimes /> : <FaBars />}</button><h1 className="text-xl font-bold md:text-2xl">{title}</h1></div><div className="flex items-center gap-3"><button aria-label="Toggle dark mode" onClick={() => setDark(!dark)} className="rounded-full p-3 hover:bg-slate-100 dark:hover:bg-slate-800">{dark ? <FaSun /> : <FaMoon />}</button><button aria-label="Notifications" className="relative rounded-full p-3 hover:bg-slate-100 dark:hover:bg-slate-800"><FaBell /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500" /></button><Link href="/profile" className="grid h-10 w-10 place-items-center rounded-full bg-accent-500 font-bold text-white" aria-label="Open profile">{(user.name || user.email || "S").charAt(0).toUpperCase()}</Link></div></header><main className="mx-auto max-w-7xl p-4 md:p-8">{children}</main></section></div>; }

